title: "Yuchen's Garage"
description: "This is a static, academic-oriented website by Yuchen Zhang"
baseurl: 
url: "https://yz81.github.io"

header_pages:
  - index.md
  - research.md
  - teaching.md
  - data.md
# -contact.md

style: hacker

footer: '<a href="https://scholar.google.com/citations?user=IHFixkAAAAAJ&hl=en">Google Scholar</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

# google_analytics: UA-xxxxxxxx-x

